### ISSUE TITLE
执行生成任务时出现nan or inf

### ISSUE THREAD

**Issue by Zjiachen** [thu-coai/LOT-Benchmark#2]
在使用源码中提供的test.source 以及下载的longlm_base模型  执行生成任务时会出现  RuntimeError: probability tensor contains either `inf`, `nan` or element < 0, 请问怎么解决呢？

**Comment by JianGuanTHU** [comment]
我们目前也没有好的解决办法，在使用其他生成模型（如BART）进行生成时也会遇到类似的问题，应该是temperature过小造成了越界
